config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get '/home', to: 'pages#home'
  
  resources :recipes                                                # Automatically creates the same routes as shown below
  
  
  

end

app/models/chef.rb
class Chef < ActiveRecord::Base
  has_many :recipes
  before_save { self.email = email.downcase }
  validates :chefname, presence: true, length: { minimum: 3, maximum: 40 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 101 },
                                    uniqueness: { case_sensitive: false },
                                    format: { with: VALID_EMAIL_REGEX }
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  validates :chef_id, presence: true
  validates :name, presence: true, length: { minimum: 5, maximum: 100 }
  validates :summary, presence: true, length: { minimum: 10, maximum: 150 }
  validates :description, presence: true, length: { minimum: 20, maximum: 500 }
  mount_uploader :picture, PictureUploader
  validate :picture_size
  
  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "Picture should be less than 5MB")
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  def index
    @recipes = Recipe.all
  end
  
  def show
    @recipe = Recipe.find(params[:id])
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params) # Will be able to mass assign and create a recipe object based on the
                                        # recipe_params method. And this will permit the name, summary and description
                                        # to flow through as these are white listed
    @recipe.chef = Chef.find(2)
    
    if @recipe.save
      flash[:success] = "Your recipe was created successfully!"
      redirect_to recipes_path
    else
      render :new
    end
  end
  
  def edit
    @recipe = Recipe.find(params[:id])
  end
  
  def update
    @recipe = Recipe.find(params[:id])
    
    if @recipe.update(recipe_params)
      flash[:success] = "Your recipe was updated successfully!"
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end
  
  private
  
    def recipe_params
      params.require(:recipe).permit(:name, :summary, :description, :picture)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def gravatar_for(chef, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: chef.chefname, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <p>MyRecipes Copyright &copy; 2015, All Rights Reserved</p>  
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |message_type, message| %> <%#-- message_type = message type, message = actual message --%>
      <div class="center alert alert-<%= message_type %>"><%= message %> <%#-- second class will change based on the message_type sent --%>
        <a class="close" data-dismiss="alert">&#215;</a> <%#-- provides the x used to close the alert --%>
      </div><%#-- /.alert alert-... --%>
    <% end %>
  </div><%#-- /.col-md-10 --%>
</div><%#-- /.row --%>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "myRecipes", root_path, class: "btn btn-lg btn-success", id: "logo" %>
      <div class="nav_item">
        <%= link_to "link 1", "", class: "btn btn-default btn-warning" %>
      </div>
      <div class="nav_item">
        <%= link_to "link 2", "", class: "btn btn-default btn-warning" %>
      </div>
      <div class="nav_item">
        <%= link_to "New Recipe", new_recipe_path, class: "btn btn-default btn-warning" %>
      </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyRecipes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  
  <%= yield %>
  
  <%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <div class="container">
    <h1>Welcome to MyRecipes App</h1>
    
    <h2>This is the home page for the Professional Ruby on Rails Developer Course on Udemy</h2>
    
    <%= link_to "Sign up now!", "", class: "btn btn-lg btn-success" %>
  </div><%#-- /.container --%>
</div><%#-- /.center jumbotron --%>

<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <h3 class="midrow">View recipes as Guest User</h3>
      <h2 class="left">Browse and view recipes as a guest and sign up later</h2>
      <p><%= link_to "Browse Recipe Listings", recipes_path, class: "btn btn-small btn-warning" %></p>
    </div><%#-- /.col-lg-4 --%>
    
    <div class="col-lg-4">
      <h3 class="midrow">View recipes as Guest User</h3>
      <h2 class="left">Browse and view recipes as a guest and sign up later</h2>
      <p><%= link_to "Browse Recipe Listings", "", class: "btn btn-small btn-warning" %></p>
    </div><%#-- /.col-lg-4 --%>
    
    <div class="col-lg-4">
      <h3 class="midrow">View recipes as Guest User</h3>
      <h2 class="left">Browse and view recipes as a guest and sign up later</h2>
      <p><%= link_to "Browse Recipe Listings", "", class: "btn btn-small btn-warning" %></p>
    </div><%#-- /.col-lg-4 --%>
  </div><%#-- /.row --%>
</div><%#-- /.container --%>

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>   <%#-- The apps/views/shared/_errors.html.erb needs to know what object is
                                              being passed.  We pass the object @recipe with the obj: @recipe code --%>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for(@recipe, html: { multiport: true }) do |f| %>  <%#-- The html: { multiport: true } code allows for the
                                                                upload of files in the form.  If we don't want to upload
                                                                files, then the code would be:
                                                                  <%= form_for @recipe do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :summary %>
      <%= f.text_field :summary %>
      
      <%= f.label :description %>
      <%= f.text_area :description, rows: 10 %>
      
      <span class="picture">    <%#-- The next three lines would not be here if we don't accept files in our form --%>
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>   <%#-- We need to add the :picture to our recipes controller white list, otherwise it will not be accepted 
                The controller can be found in apps/controllers/recipes_controller.rb --%>
      
      <%= f.submit(@recipe.new_record? ? "Create Recipe" : "Edit Recipe", class: "btn btn-success") %>
    <% end %>
  </div><%#-- /.well col-md-8 col-md-offset-2 --%>
</div><%#-- /.row --%>

<script type="text/javascript">
  $('#recipe_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file');
    }
  });
</script>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit Recipe" %> <%# It calls the apps/views/shared/_page_title.html.erb 
                                                        partial and sends the title Edit Recipe to be used in the partial %>

<%= render 'form' %> <%#-- This renders the form partial found in apps/views/recipes _form.html.erb --%>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "All Recipes" %> <%# It calls the apps/views/shared/_page_title.html.erb 
                                                        partial and sends the title All Recipes to be used in the partial %>

<div class="container">
  <%  @recipes.each do |recipe| %>
  
    <div class="row">
      <div class="col-md-2">
        <section class="chef_info center">
          <%= gravatar_for recipe.chef, size: 100 %>    <%#-- The gravatar_for method will be created by us.  
                                                        The size can change based on where we put the Gravatar
                                                        in the sited --%>
          <h5>Chef name: <%= recipe.chef.chefname %> </h5>    <%#-- This code works because we have an association --%>
        </section><%#-- /.section --%>
      </div><%#-- /.col-md-2 --%>
    
      <div class="col-lg-6 well"><%#-- well is a bootstrap class that shows a grey box around a section --%>
        <h4> <%= link_to recipe.name, recipe_path(recipe) %> </h4>
        <p> <%= recipe.summary %> </p>
        <p>
          <span class="quiet"><small> Created: <%= time_ago_in_words(recipe.created_at) %> ago </small></span>
                                        <%#-- time_ago_in_words is a Rails provided method that takes an argument 
                                        for a date and will display the information in a very user friendly format --%>
        </p>
      </div><%#-- /.col-lg-6 well --%>
      <div class="col-md-4">
        <%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar") if recipe.picture? %>
                                        <%#-- The if recipe.picture? part of the code will show the picture if there
                                        is a picture to show in the database. %>
      </div>
    </div><%#-- /.row --%>
    <hr>
    
  <% end %>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "Create a new Recipe" %>   <%# It calls the apps/views/shared/_page_title.html.erb 
                                                                  partial and sends the title Create a new Recipe to be 
                                                                  used in the partial %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<div class="container">
  
<%= render 'shared/page_title', title: @recipe.name %> <%# It calls the apps/views/shared/_page_title.html.erb 
                                                        partial and sends the name of the recipe via the @recipe.name
                                                        as the title to be used in the partial %>

  <div class="row">
    <div class="col-md-4 pull-right center">
      <%= gravatar_for @recipe.chef, size: 200 %>
        <h5>Brought to you by: <%= @recipe.chef.chefname %></h5>
    </div><%#-- /.col-md-4 pull-right center --%>
    <div class="col-md-8">
      <%= link_to "Edit this Recipe", edit_recipe_path(@recipe), class: "btn btn-success pull-right" %>
      <h3> <%= @recipe.summary  %> </h3>
      <div class="show_recipe">
        <%= image_tag(@recipe.picture.url, class: "gravatar") if @recipe.picture? %>
      </div>
      <div class="well">
        <p>
          <strong>Steps:</strong>
        </p>
          <%= simple_format(@recipe.description) %> <%#-- The simple_format() is used to presend the information in
                                                    the description the same way it was typed (lists show as list, etc.)--%>
      </div><%#-- /.well --%>
    </div><%#-- /.col-md-8 --%>
  </div><%#-- /.row --%>

  <h5><%= link_to "Return to Recipes Listing", recipes_path, class: "btn btn-warning btn-small" %></h5>
  
</div><%#-- /.container --%>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>  <%# An object is being passed to this form into the obj %>
  <div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2">
      <h5>Please correct the following errors:</h5>
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<p>
  <h1><%= title %></h1> <%# A title is sent from the page that is calling this partial %>
  <hr>
</p>